export const TYPES = {
  UPDATE_WEB3_PROVIDER: "UPDATE_WEB3_PROVIDER",
  UPDATE_WEB3: "UPDATE_WEB3",
  UPDATE_BALANCE: "UPDATE_BALANCE",
  DISCONNECT_WALLET: "DISCONNECT_WALLET",

  /*----------------------------------------*/
  UDATE_CHAIN_DETAILS: "UDATE_CHAIN_DETAILS",
  UPDATE_CONNECTED_WALLET: "CONNECT_WALLET",
  WALLET_CONNECTED: "WALLET_CONNECTED",

  WALLET_CONNECT_INITIALIZED: "WALLET_CONNECT_INITIALIZED",
  WEB3_JS_LOADED: "WEB3_JS_LOADED",
};
